// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Okprojecttask is an object representing the database table.
type Okprojecttask struct {
	IDPTask      int       `boil:"id_p_task" json:"id_p_task" toml:"id_p_task" yaml:"id_p_task"`
	ProjectID    int       `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	TaskID       int       `boil:"task_id" json:"task_id" toml:"task_id" yaml:"task_id"`
	AssignedtoID int       `boil:"assignedto_id" json:"assignedto_id" toml:"assignedto_id" yaml:"assignedto_id"`
	AssignerID   int       `boil:"assigner_id" json:"assigner_id" toml:"assigner_id" yaml:"assigner_id"`
	CreatedAt    null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Status       string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	DueDate      null.Time `boil:"due_date" json:"due_date,omitempty" toml:"due_date" yaml:"due_date,omitempty"`

	R *okprojecttaskR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L okprojecttaskL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// okprojecttaskR is where relationships are stored.
type okprojecttaskR struct {
	Assignedto *Okprofile
	Assigner   *Okprofile
	Project    *Okproject
	Task       *Oktask
}

// okprojecttaskL is where Load methods for each relationship are stored.
type okprojecttaskL struct{}

var (
	okprojecttaskColumns               = []string{"id_p_task", "project_id", "task_id", "assignedto_id", "assigner_id", "created_at", "updated_at", "status", "due_date"}
	okprojecttaskColumnsWithoutDefault = []string{"project_id", "task_id", "assignedto_id", "assigner_id", "created_at", "updated_at", "status", "due_date"}
	okprojecttaskColumnsWithDefault    = []string{"id_p_task"}
	okprojecttaskPrimaryKeyColumns     = []string{"id_p_task"}
)

type (
	// OkprojecttaskSlice is an alias for a slice of pointers to Okprojecttask.
	// This should generally be used opposed to []Okprojecttask.
	OkprojecttaskSlice []*Okprojecttask
	// OkprojecttaskHook is the signature for custom Okprojecttask hook methods
	OkprojecttaskHook func(boil.Executor, *Okprojecttask) error

	okprojecttaskQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	okprojecttaskType                 = reflect.TypeOf(&Okprojecttask{})
	okprojecttaskMapping              = queries.MakeStructMapping(okprojecttaskType)
	okprojecttaskPrimaryKeyMapping, _ = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, okprojecttaskPrimaryKeyColumns)
	okprojecttaskInsertCacheMut       sync.RWMutex
	okprojecttaskInsertCache          = make(map[string]insertCache)
	okprojecttaskUpdateCacheMut       sync.RWMutex
	okprojecttaskUpdateCache          = make(map[string]updateCache)
	okprojecttaskUpsertCacheMut       sync.RWMutex
	okprojecttaskUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var okprojecttaskBeforeInsertHooks []OkprojecttaskHook
var okprojecttaskBeforeUpdateHooks []OkprojecttaskHook
var okprojecttaskBeforeDeleteHooks []OkprojecttaskHook
var okprojecttaskBeforeUpsertHooks []OkprojecttaskHook

var okprojecttaskAfterInsertHooks []OkprojecttaskHook
var okprojecttaskAfterSelectHooks []OkprojecttaskHook
var okprojecttaskAfterUpdateHooks []OkprojecttaskHook
var okprojecttaskAfterDeleteHooks []OkprojecttaskHook
var okprojecttaskAfterUpsertHooks []OkprojecttaskHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Okprojecttask) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Okprojecttask) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Okprojecttask) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Okprojecttask) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Okprojecttask) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Okprojecttask) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Okprojecttask) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Okprojecttask) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Okprojecttask) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range okprojecttaskAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOkprojecttaskHook registers your hook function for all future operations.
func AddOkprojecttaskHook(hookPoint boil.HookPoint, okprojecttaskHook OkprojecttaskHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		okprojecttaskBeforeInsertHooks = append(okprojecttaskBeforeInsertHooks, okprojecttaskHook)
	case boil.BeforeUpdateHook:
		okprojecttaskBeforeUpdateHooks = append(okprojecttaskBeforeUpdateHooks, okprojecttaskHook)
	case boil.BeforeDeleteHook:
		okprojecttaskBeforeDeleteHooks = append(okprojecttaskBeforeDeleteHooks, okprojecttaskHook)
	case boil.BeforeUpsertHook:
		okprojecttaskBeforeUpsertHooks = append(okprojecttaskBeforeUpsertHooks, okprojecttaskHook)
	case boil.AfterInsertHook:
		okprojecttaskAfterInsertHooks = append(okprojecttaskAfterInsertHooks, okprojecttaskHook)
	case boil.AfterSelectHook:
		okprojecttaskAfterSelectHooks = append(okprojecttaskAfterSelectHooks, okprojecttaskHook)
	case boil.AfterUpdateHook:
		okprojecttaskAfterUpdateHooks = append(okprojecttaskAfterUpdateHooks, okprojecttaskHook)
	case boil.AfterDeleteHook:
		okprojecttaskAfterDeleteHooks = append(okprojecttaskAfterDeleteHooks, okprojecttaskHook)
	case boil.AfterUpsertHook:
		okprojecttaskAfterUpsertHooks = append(okprojecttaskAfterUpsertHooks, okprojecttaskHook)
	}
}

// OneP returns a single okprojecttask record from the query, and panics on error.
func (q okprojecttaskQuery) OneP() *Okprojecttask {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single okprojecttask record from the query.
func (q okprojecttaskQuery) One() (*Okprojecttask, error) {
	o := &Okprojecttask{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for okprojecttask")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Okprojecttask records from the query, and panics on error.
func (q okprojecttaskQuery) AllP() OkprojecttaskSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Okprojecttask records from the query.
func (q okprojecttaskQuery) All() (OkprojecttaskSlice, error) {
	var o OkprojecttaskSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Okprojecttask slice")
	}

	if len(okprojecttaskAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Okprojecttask records in the query, and panics on error.
func (q okprojecttaskQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Okprojecttask records in the query.
func (q okprojecttaskQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count okprojecttask rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q okprojecttaskQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q okprojecttaskQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if okprojecttask exists")
	}

	return count > 0, nil
}

// AssignedtoG pointed to by the foreign key.
func (o *Okprojecttask) AssignedtoG(mods ...qm.QueryMod) okprofileQuery {
	return o.Assignedto(boil.GetDB(), mods...)
}

// Assignedto pointed to by the foreign key.
func (o *Okprojecttask) Assignedto(exec boil.Executor, mods ...qm.QueryMod) okprofileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id_profile=?", o.AssignedtoID),
	}

	queryMods = append(queryMods, mods...)

	query := Okprofiles(exec, queryMods...)
	queries.SetFrom(query.Query, "`okprofile`")

	return query
}

// AssignerG pointed to by the foreign key.
func (o *Okprojecttask) AssignerG(mods ...qm.QueryMod) okprofileQuery {
	return o.Assigner(boil.GetDB(), mods...)
}

// Assigner pointed to by the foreign key.
func (o *Okprojecttask) Assigner(exec boil.Executor, mods ...qm.QueryMod) okprofileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id_profile=?", o.AssignerID),
	}

	queryMods = append(queryMods, mods...)

	query := Okprofiles(exec, queryMods...)
	queries.SetFrom(query.Query, "`okprofile`")

	return query
}

// ProjectG pointed to by the foreign key.
func (o *Okprojecttask) ProjectG(mods ...qm.QueryMod) okprojectQuery {
	return o.Project(boil.GetDB(), mods...)
}

// Project pointed to by the foreign key.
func (o *Okprojecttask) Project(exec boil.Executor, mods ...qm.QueryMod) okprojectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id_project=?", o.ProjectID),
	}

	queryMods = append(queryMods, mods...)

	query := Okprojects(exec, queryMods...)
	queries.SetFrom(query.Query, "`okproject`")

	return query
}

// TaskG pointed to by the foreign key.
func (o *Okprojecttask) TaskG(mods ...qm.QueryMod) oktaskQuery {
	return o.Task(boil.GetDB(), mods...)
}

// Task pointed to by the foreign key.
func (o *Okprojecttask) Task(exec boil.Executor, mods ...qm.QueryMod) oktaskQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id_task=?", o.TaskID),
	}

	queryMods = append(queryMods, mods...)

	query := Oktasks(exec, queryMods...)
	queries.SetFrom(query.Query, "`oktask`")

	return query
}

// LoadAssignedto allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (okprojecttaskL) LoadAssignedto(e boil.Executor, singular bool, maybeOkprojecttask interface{}) error {
	var slice []*Okprojecttask
	var object *Okprojecttask

	count := 1
	if singular {
		object = maybeOkprojecttask.(*Okprojecttask)
	} else {
		slice = *maybeOkprojecttask.(*OkprojecttaskSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &okprojecttaskR{}
		}
		args[0] = object.AssignedtoID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &okprojecttaskR{}
			}
			args[i] = obj.AssignedtoID
		}
	}

	query := fmt.Sprintf(
		"select * from `okprofile` where `id_profile` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Okprofile")
	}
	defer results.Close()

	var resultSlice []*Okprofile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Okprofile")
	}

	if len(okprojecttaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Assignedto = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AssignedtoID == foreign.IDProfile {
				local.R.Assignedto = foreign
				break
			}
		}
	}

	return nil
}

// LoadAssigner allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (okprojecttaskL) LoadAssigner(e boil.Executor, singular bool, maybeOkprojecttask interface{}) error {
	var slice []*Okprojecttask
	var object *Okprojecttask

	count := 1
	if singular {
		object = maybeOkprojecttask.(*Okprojecttask)
	} else {
		slice = *maybeOkprojecttask.(*OkprojecttaskSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &okprojecttaskR{}
		}
		args[0] = object.AssignerID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &okprojecttaskR{}
			}
			args[i] = obj.AssignerID
		}
	}

	query := fmt.Sprintf(
		"select * from `okprofile` where `id_profile` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Okprofile")
	}
	defer results.Close()

	var resultSlice []*Okprofile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Okprofile")
	}

	if len(okprojecttaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Assigner = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AssignerID == foreign.IDProfile {
				local.R.Assigner = foreign
				break
			}
		}
	}

	return nil
}

// LoadProject allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (okprojecttaskL) LoadProject(e boil.Executor, singular bool, maybeOkprojecttask interface{}) error {
	var slice []*Okprojecttask
	var object *Okprojecttask

	count := 1
	if singular {
		object = maybeOkprojecttask.(*Okprojecttask)
	} else {
		slice = *maybeOkprojecttask.(*OkprojecttaskSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &okprojecttaskR{}
		}
		args[0] = object.ProjectID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &okprojecttaskR{}
			}
			args[i] = obj.ProjectID
		}
	}

	query := fmt.Sprintf(
		"select * from `okproject` where `id_project` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Okproject")
	}
	defer results.Close()

	var resultSlice []*Okproject
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Okproject")
	}

	if len(okprojecttaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Project = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProjectID == foreign.IDProject {
				local.R.Project = foreign
				break
			}
		}
	}

	return nil
}

// LoadTask allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (okprojecttaskL) LoadTask(e boil.Executor, singular bool, maybeOkprojecttask interface{}) error {
	var slice []*Okprojecttask
	var object *Okprojecttask

	count := 1
	if singular {
		object = maybeOkprojecttask.(*Okprojecttask)
	} else {
		slice = *maybeOkprojecttask.(*OkprojecttaskSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &okprojecttaskR{}
		}
		args[0] = object.TaskID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &okprojecttaskR{}
			}
			args[i] = obj.TaskID
		}
	}

	query := fmt.Sprintf(
		"select * from `oktask` where `id_task` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Oktask")
	}
	defer results.Close()

	var resultSlice []*Oktask
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Oktask")
	}

	if len(okprojecttaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Task = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TaskID == foreign.IDTask {
				local.R.Task = foreign
				break
			}
		}
	}

	return nil
}

// SetAssignedtoG of the okprojecttask to the related item.
// Sets o.R.Assignedto to related.
// Adds o to related.R.AssignedtoOkprojecttasks.
// Uses the global database handle.
func (o *Okprojecttask) SetAssignedtoG(insert bool, related *Okprofile) error {
	return o.SetAssignedto(boil.GetDB(), insert, related)
}

// SetAssignedtoP of the okprojecttask to the related item.
// Sets o.R.Assignedto to related.
// Adds o to related.R.AssignedtoOkprojecttasks.
// Panics on error.
func (o *Okprojecttask) SetAssignedtoP(exec boil.Executor, insert bool, related *Okprofile) {
	if err := o.SetAssignedto(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAssignedtoGP of the okprojecttask to the related item.
// Sets o.R.Assignedto to related.
// Adds o to related.R.AssignedtoOkprojecttasks.
// Uses the global database handle and panics on error.
func (o *Okprojecttask) SetAssignedtoGP(insert bool, related *Okprofile) {
	if err := o.SetAssignedto(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAssignedto of the okprojecttask to the related item.
// Sets o.R.Assignedto to related.
// Adds o to related.R.AssignedtoOkprojecttasks.
func (o *Okprojecttask) SetAssignedto(exec boil.Executor, insert bool, related *Okprofile) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `okprojecttask` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"assignedto_id"}),
		strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns),
	)
	values := []interface{}{related.IDProfile, o.IDPTask}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AssignedtoID = related.IDProfile

	if o.R == nil {
		o.R = &okprojecttaskR{
			Assignedto: related,
		}
	} else {
		o.R.Assignedto = related
	}

	if related.R == nil {
		related.R = &okprofileR{
			AssignedtoOkprojecttasks: OkprojecttaskSlice{o},
		}
	} else {
		related.R.AssignedtoOkprojecttasks = append(related.R.AssignedtoOkprojecttasks, o)
	}

	return nil
}

// SetAssignerG of the okprojecttask to the related item.
// Sets o.R.Assigner to related.
// Adds o to related.R.AssignerOkprojecttasks.
// Uses the global database handle.
func (o *Okprojecttask) SetAssignerG(insert bool, related *Okprofile) error {
	return o.SetAssigner(boil.GetDB(), insert, related)
}

// SetAssignerP of the okprojecttask to the related item.
// Sets o.R.Assigner to related.
// Adds o to related.R.AssignerOkprojecttasks.
// Panics on error.
func (o *Okprojecttask) SetAssignerP(exec boil.Executor, insert bool, related *Okprofile) {
	if err := o.SetAssigner(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAssignerGP of the okprojecttask to the related item.
// Sets o.R.Assigner to related.
// Adds o to related.R.AssignerOkprojecttasks.
// Uses the global database handle and panics on error.
func (o *Okprojecttask) SetAssignerGP(insert bool, related *Okprofile) {
	if err := o.SetAssigner(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAssigner of the okprojecttask to the related item.
// Sets o.R.Assigner to related.
// Adds o to related.R.AssignerOkprojecttasks.
func (o *Okprojecttask) SetAssigner(exec boil.Executor, insert bool, related *Okprofile) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `okprojecttask` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"assigner_id"}),
		strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns),
	)
	values := []interface{}{related.IDProfile, o.IDPTask}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AssignerID = related.IDProfile

	if o.R == nil {
		o.R = &okprojecttaskR{
			Assigner: related,
		}
	} else {
		o.R.Assigner = related
	}

	if related.R == nil {
		related.R = &okprofileR{
			AssignerOkprojecttasks: OkprojecttaskSlice{o},
		}
	} else {
		related.R.AssignerOkprojecttasks = append(related.R.AssignerOkprojecttasks, o)
	}

	return nil
}

// SetProjectG of the okprojecttask to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectOkprojecttasks.
// Uses the global database handle.
func (o *Okprojecttask) SetProjectG(insert bool, related *Okproject) error {
	return o.SetProject(boil.GetDB(), insert, related)
}

// SetProjectP of the okprojecttask to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectOkprojecttasks.
// Panics on error.
func (o *Okprojecttask) SetProjectP(exec boil.Executor, insert bool, related *Okproject) {
	if err := o.SetProject(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetProjectGP of the okprojecttask to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectOkprojecttasks.
// Uses the global database handle and panics on error.
func (o *Okprojecttask) SetProjectGP(insert bool, related *Okproject) {
	if err := o.SetProject(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetProject of the okprojecttask to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectOkprojecttasks.
func (o *Okprojecttask) SetProject(exec boil.Executor, insert bool, related *Okproject) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `okprojecttask` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"project_id"}),
		strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns),
	)
	values := []interface{}{related.IDProject, o.IDPTask}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProjectID = related.IDProject

	if o.R == nil {
		o.R = &okprojecttaskR{
			Project: related,
		}
	} else {
		o.R.Project = related
	}

	if related.R == nil {
		related.R = &okprojectR{
			ProjectOkprojecttasks: OkprojecttaskSlice{o},
		}
	} else {
		related.R.ProjectOkprojecttasks = append(related.R.ProjectOkprojecttasks, o)
	}

	return nil
}

// SetTaskG of the okprojecttask to the related item.
// Sets o.R.Task to related.
// Adds o to related.R.TaskOkprojecttasks.
// Uses the global database handle.
func (o *Okprojecttask) SetTaskG(insert bool, related *Oktask) error {
	return o.SetTask(boil.GetDB(), insert, related)
}

// SetTaskP of the okprojecttask to the related item.
// Sets o.R.Task to related.
// Adds o to related.R.TaskOkprojecttasks.
// Panics on error.
func (o *Okprojecttask) SetTaskP(exec boil.Executor, insert bool, related *Oktask) {
	if err := o.SetTask(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTaskGP of the okprojecttask to the related item.
// Sets o.R.Task to related.
// Adds o to related.R.TaskOkprojecttasks.
// Uses the global database handle and panics on error.
func (o *Okprojecttask) SetTaskGP(insert bool, related *Oktask) {
	if err := o.SetTask(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTask of the okprojecttask to the related item.
// Sets o.R.Task to related.
// Adds o to related.R.TaskOkprojecttasks.
func (o *Okprojecttask) SetTask(exec boil.Executor, insert bool, related *Oktask) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `okprojecttask` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"task_id"}),
		strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns),
	)
	values := []interface{}{related.IDTask, o.IDPTask}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TaskID = related.IDTask

	if o.R == nil {
		o.R = &okprojecttaskR{
			Task: related,
		}
	} else {
		o.R.Task = related
	}

	if related.R == nil {
		related.R = &oktaskR{
			TaskOkprojecttasks: OkprojecttaskSlice{o},
		}
	} else {
		related.R.TaskOkprojecttasks = append(related.R.TaskOkprojecttasks, o)
	}

	return nil
}

// OkprojecttasksG retrieves all records.
func OkprojecttasksG(mods ...qm.QueryMod) okprojecttaskQuery {
	return Okprojecttasks(boil.GetDB(), mods...)
}

// Okprojecttasks retrieves all the records using an executor.
func Okprojecttasks(exec boil.Executor, mods ...qm.QueryMod) okprojecttaskQuery {
	mods = append(mods, qm.From("`okprojecttask`"))
	return okprojecttaskQuery{NewQuery(exec, mods...)}
}

// FindOkprojecttaskG retrieves a single record by ID.
func FindOkprojecttaskG(idPTask int, selectCols ...string) (*Okprojecttask, error) {
	return FindOkprojecttask(boil.GetDB(), idPTask, selectCols...)
}

// FindOkprojecttaskGP retrieves a single record by ID, and panics on error.
func FindOkprojecttaskGP(idPTask int, selectCols ...string) *Okprojecttask {
	retobj, err := FindOkprojecttask(boil.GetDB(), idPTask, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindOkprojecttask retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOkprojecttask(exec boil.Executor, idPTask int, selectCols ...string) (*Okprojecttask, error) {
	okprojecttaskObj := &Okprojecttask{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `okprojecttask` where `id_p_task`=?", sel,
	)

	q := queries.Raw(exec, query, idPTask)

	err := q.Bind(okprojecttaskObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from okprojecttask")
	}

	return okprojecttaskObj, nil
}

// FindOkprojecttaskP retrieves a single record by ID with an executor, and panics on error.
func FindOkprojecttaskP(exec boil.Executor, idPTask int, selectCols ...string) *Okprojecttask {
	retobj, err := FindOkprojecttask(exec, idPTask, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Okprojecttask) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Okprojecttask) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Okprojecttask) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Okprojecttask) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no okprojecttask provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(okprojecttaskColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	okprojecttaskInsertCacheMut.RLock()
	cache, cached := okprojecttaskInsertCache[key]
	okprojecttaskInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			okprojecttaskColumns,
			okprojecttaskColumnsWithDefault,
			okprojecttaskColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `okprojecttask` (`%s`) VALUES (%s)", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `okprojecttask` () VALUES ()"
		}

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `okprojecttask` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into okprojecttask")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.IDPTask = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == okprojecttaskMapping["IDPTask"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.IDPTask,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for okprojecttask")
	}

CacheNoHooks:
	if !cached {
		okprojecttaskInsertCacheMut.Lock()
		okprojecttaskInsertCache[key] = cache
		okprojecttaskInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Okprojecttask record. See Update for
// whitelist behavior description.
func (o *Okprojecttask) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Okprojecttask record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Okprojecttask) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Okprojecttask, and panics on error.
// See Update for whitelist behavior description.
func (o *Okprojecttask) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Okprojecttask.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Okprojecttask) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	okprojecttaskUpdateCacheMut.RLock()
	cache, cached := okprojecttaskUpdateCache[key]
	okprojecttaskUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(okprojecttaskColumns, okprojecttaskPrimaryKeyColumns, whitelist)
		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update okprojecttask, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `okprojecttask` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, okprojecttaskPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, append(wl, okprojecttaskPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update okprojecttask row")
	}

	if !cached {
		okprojecttaskUpdateCacheMut.Lock()
		okprojecttaskUpdateCache[key] = cache
		okprojecttaskUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q okprojecttaskQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q okprojecttaskQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for okprojecttask")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o OkprojecttaskSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o OkprojecttaskSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o OkprojecttaskSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OkprojecttaskSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), okprojecttaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"UPDATE `okprojecttask` SET %s WHERE (`id_p_task`) IN (%s)",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(okprojecttaskPrimaryKeyColumns), len(colNames)+1, len(okprojecttaskPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in okprojecttask slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Okprojecttask) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Okprojecttask) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Okprojecttask) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Okprojecttask) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no okprojecttask provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(okprojecttaskColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	okprojecttaskUpsertCacheMut.RLock()
	cache, cached := okprojecttaskUpsertCache[key]
	okprojecttaskUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			okprojecttaskColumns,
			okprojecttaskColumnsWithDefault,
			okprojecttaskColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			okprojecttaskColumns,
			okprojecttaskPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert okprojecttask, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "okprojecttask", update, whitelist)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `okprojecttask` WHERE `id_p_task`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(okprojecttaskType, okprojecttaskMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for okprojecttask")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.IDPTask = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == okprojecttaskMapping["IDPTask"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.IDPTask,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for okprojecttask")
	}

CacheNoHooks:
	if !cached {
		okprojecttaskUpsertCacheMut.Lock()
		okprojecttaskUpsertCache[key] = cache
		okprojecttaskUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Okprojecttask record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Okprojecttask) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Okprojecttask record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Okprojecttask) DeleteG() error {
	if o == nil {
		return errors.New("models: no Okprojecttask provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Okprojecttask record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Okprojecttask) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Okprojecttask record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Okprojecttask) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Okprojecttask provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), okprojecttaskPrimaryKeyMapping)
	sql := "DELETE FROM `okprojecttask` WHERE `id_p_task`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from okprojecttask")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q okprojecttaskQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q okprojecttaskQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no okprojecttaskQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from okprojecttask")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o OkprojecttaskSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o OkprojecttaskSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Okprojecttask slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o OkprojecttaskSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OkprojecttaskSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Okprojecttask slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(okprojecttaskBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), okprojecttaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"DELETE FROM `okprojecttask` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, okprojecttaskPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(okprojecttaskPrimaryKeyColumns), 1, len(okprojecttaskPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from okprojecttask slice")
	}

	if len(okprojecttaskAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Okprojecttask) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Okprojecttask) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Okprojecttask) ReloadG() error {
	if o == nil {
		return errors.New("models: no Okprojecttask provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Okprojecttask) Reload(exec boil.Executor) error {
	ret, err := FindOkprojecttask(exec, o.IDPTask)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *OkprojecttaskSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *OkprojecttaskSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OkprojecttaskSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty OkprojecttaskSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OkprojecttaskSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	okprojecttasks := OkprojecttaskSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), okprojecttaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"SELECT `okprojecttask`.* FROM `okprojecttask` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, okprojecttaskPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(okprojecttaskPrimaryKeyColumns), 1, len(okprojecttaskPrimaryKeyColumns)),
	)

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&okprojecttasks)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OkprojecttaskSlice")
	}

	*o = okprojecttasks

	return nil
}

// OkprojecttaskExists checks if the Okprojecttask row exists.
func OkprojecttaskExists(exec boil.Executor, idPTask int) (bool, error) {
	var exists bool

	sql := "select exists(select 1 from `okprojecttask` where `id_p_task`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, idPTask)
	}

	row := exec.QueryRow(sql, idPTask)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if okprojecttask exists")
	}

	return exists, nil
}

// OkprojecttaskExistsG checks if the Okprojecttask row exists.
func OkprojecttaskExistsG(idPTask int) (bool, error) {
	return OkprojecttaskExists(boil.GetDB(), idPTask)
}

// OkprojecttaskExistsGP checks if the Okprojecttask row exists. Panics on error.
func OkprojecttaskExistsGP(idPTask int) bool {
	e, err := OkprojecttaskExists(boil.GetDB(), idPTask)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// OkprojecttaskExistsP checks if the Okprojecttask row exists. Panics on error.
func OkprojecttaskExistsP(exec boil.Executor, idPTask int) bool {
	e, err := OkprojecttaskExists(exec, idPTask)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
